(define-module (bawwab)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (gnu packages)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages python-web)
  #:use-module (gnu packages check)
  #:use-module (gnu packages time)
  #:use-module (gnu packages fonts)
  #:use-module (gnu packages databases)
  #:use-module (zpid packages asyncssh)
  #:use-module (zpid packages sanic)
  #:use-module ((zpid packages tortoise) #:prefix zpid:)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build-system python)
  #:use-module (guix gexp)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-26))

(define %source-dir (dirname (dirname (current-filename))))

(package
  (name "bawwab")
  (version "0.1")
  (source (local-file %source-dir #:recursive? #t))
  (build-system python-build-system)
  (arguments `(#:tests? #f))
  (propagated-inputs
   `(("python-asyncssh" ,python-asyncssh)
     ("python-yarl" ,python-yarl)
     ("python-sanic" ,python-sanic)
     ("python-aiohttp" ,python-aiohttp)
     ("python-pytz" ,python-pytz)
     ("font-awesome" ,font-awesome)
     ("python-tortoise-orm" ,zpid:python-tortoise-orm)
     ("python-aiosqlite" ,python-aiosqlite)))
  (home-page #f)
  (synopsis #f)
  (description #f)
  (license #f))

